---
  - name: Build Docker
    hosts: localhost
    vars_files:
      - vars.yml

    tasks:
      - name: Check connection node
        become: true
        ping:
      
      - name: Install Docker
        become: true
        yum:
          name: docker
          state: present
      
      - name: Ensure docker is running
        become: true
        service:
          name: docker
          state: started
          enabled: yes
      
      - name: Add user to group Docker
        become: true
        user:
          name: ansman
          shell: /bin/bash
          groups: docker
          append: yes
          
      - name: "Ensure git installed"
        become: true
        yum:
          name: git
          state: present
      
      - name: "Installing Python Docker"
        become: true
        pip:
          name: docker
      
      - name: "Clone Git Repository"
        git:
          repo: "{{repo}}"
          dest: "{{dests}}/{{proj}}"
          version: "{{branch}}"
      
      - name: "Build image"
        community.general.docker_image:
          name: "{{hub}}/{{proj}}:{{branch}}"
          build:
            path: "{{dests}}/{{proj}}"
            dockerfile: DockerfileDev
          source: build